# Generated by Django 5.2.7 on 2025-10-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salesperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
