# Generated by Django 5.2.7 on 2025-10-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="pic",
            field=models.CharField(
                default="/static/img/no_picture.jpg", max_length=255
            ),
        ),
    ]
